# @author DieFriiks / CustomCraftDev / undeaD_D
# @link www.custom-craft.de
# @github https://github.com/CustomCraftDev/killerarrows

enable-crafting: true
craft1: DIAMOND
craft2: STICK
craft3: FEATHER

all-arrows-ohko: false
all-arrows-cost: false
arrow-damage: 20.0
arrow-cost: 100.0

msg-eco-error: insufficient funds :(
msg-arrow-bought: OHKO Arrow bought.
msg-arrow-equip: Special Arrow equiped
msg-arrow-dequip: Special Arrow already equiped
msg-arrow-shot: Special Arrow shot

blacklisted-entities:
  - ENDER_CRYSTAL
  - ENDER_DRAGON
  - GIANT
  - WITHER
  - WITHER_SKULL
blacklisted-players:
  - undeaD_D
  - undeaD_Bot
  - Notch
players:
