# @author DieFriiks / CustomCraftDev / undeaD_D
# @link www.custom-craft.de
# @github https://github.com/CustomCraftDev/killerarrows

crafting:
  enable: true
  craft1: DIAMOND
  craft2: STICK
  craft3: FEATHER

info-only:
  var0: 'these things only work on messages (only var1 and var4 work on ohko-arrow)'
  var1: 'colorcodes: https://github.com/CustomCraftDev/perplayercommands'
  var2: '%playername% gets replaced with the name of the player'
  var3: '%world% gets replaced with the world the player is currently in'
  var4: '%nextline% indicates a new line in the chat'
  var5: '%no% indicates that there should be nothing to be displayed'

ohko-arrow:
  name: '&cOHKO Arrow'
  lore: '&7When you hit someone with this arrow with a bow,%nextline%they will die instantly!%nextline%rightclick to equip/unequip%nextline%DO NOT STACK THEM !!!'
  enchantment-lvl: 10
  all-arrows-ohko: false
  all-arrows-cost: false
  arrow-damage: 20.0
  arrow-cost: 100.0

msg:
  disable: '&c[KillerArrows] was disabled'
  reset: '&c[KillerArrows] was reset'
  reload: '&c[KillerArrows] was reloaded'
  eco-error: insufficient funds :(
  arrow-bought: OHKO Arrow bought.
  arrow-equipped: Special Arrow equipped
  arrow-dequipped: Special Arrow already equipped
  arrow-shot: Special Arrow shot

blacklisted-entities:
  - ENDER_CRYSTAL
  - ENDER_DRAGON
  - GIANT
  - WITHER
  - WITHER_SKULL
blacklisted-players:
  - undeaD_D
  - undeaD_Bot
  - Notch
players:
